name: build documentation with Sphinx and put it in the docs/ directory for github pages

on:
  pull_request:
    branches:
      - main
      - design
  push:
    branches:
      - design
   
jobs:
  doc:
    runs-on: ubuntu-latest
    env:
      docdir: docs/
      python_version: 3.8
      
    steps:
    - name: Temporary developer checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
        path: instrumentDataBaseAPI
    
    - name: Set up Python $python_version
      uses: actions/setup-python@v2
      with:
        python-version: $python-version

    - name: Install dependencies
      run: |
        cd instrumentDataBaseAPI
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install -e .

    - name: Generate documentation
      run: |
        cd doc
        make html
        cd -
        git rm $docdir
        mv doc/build $docdir
        git add $docdir
        git commit -m "update published documentation"
        git push
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH }}

