name: build documentation with Sphinx and put it in the docs/ directory for github pages

on:
  pull_request:
    branches:
      - main
      - design
  push:
    branches:
      - design
   
jobs:
  doc:
    runs-on: ubuntu-latest
    env:
      docdir: docs/
      pythonversion: 3.8
      local_path: instrumentDataBaseAPI

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH }}
        path: ${{ env.local_path }}
        persist-credentials: false
    
    - name: Set up Python ${{ env.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.pythonversion }}

    - name: Install dependencies
      run: |
        sudo apt install pandoc
        cd $local_path
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install -r doc/requirements.txt
        pip install -e .

    - name: Generate documentation
      run: |
        cd $local_path
        git config --local user.email "githubaction@noreply.com"
        git config --local user.name "Github Actions"
        cd doc
        make html
        cd -
        git rm -r $docdir
        mv doc/build $docdir
        git add $docdir
        git commit -m "update published documentation"
        git push

