name: build documentation with Sphinx and put it in the docs/ directory for github pages

on:
  pull_request:
    branches:
      - main
      - design
  push:
    branches:
      - design
   
jobs:
  doc:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      
    env:
      docdir: docs/html/
      pythonversion: 3.8
      local_path: instrumentDataBaseAPI

    steps:
      - uses: actions/checkout@v3
        
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.docdir }}
          publish_branch: gh-pages
          
