name: instrument database API unit tests on ubuntu

on:
  push:
    branches:
      - design
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        mcstas-version: [2.7]
    runs-on: ubuntu-latest
    env:
      MCSTAS: /usr/share/mcstas/${{ matrix.mcstas-version }}

    steps:
    - name: Temporary developer checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
        path: instrumentDataBaseAPI
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd instrumentDataBaseAPI
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install -e .

    - name: Lint with flake8
      run: |
        cd instrumentDataBaseAPI
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Black check
      run: |
        black --check --diff
        
    - name: Install McStas
      run: |
        cd /etc/apt/sources.list.d
        sudo wget http://packages.mccode.org/debian/mccode.list
        sudo apt-get update
        sudo apt-get install mcstas-suite-python mcstas-${{ matrix.mcstas-version }}
          
    - name: Show file structure
      run: tree .

    - name: Run unit tests
      run: |
        python -m pytest instrumentDataBaseAPI/tests/

